apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-auth
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.auth.secret | b64enc | quote }}
